### PR TITLE
(AzureCXP) Fix for MicrosoftDocs/azure-docs#26607

### PR DESCRIPTION
**Pull request by KalyanChanumolu-MSFT**
Reorganizing methods to address GitIssue 
https://github.com/MicrosoftDocs/azure-docs/issues/26607

### CODE REVIEW

**Comment by KalyanChanumolu-MSFT** [comment]
#sign-off

**Comment by KalyanChanumolu-MSFT** [comment]
@SnehaGunda Could you please review and help merge this PR

**Comment by SnehaGunda** [comment]
@KalyanChanumolu-MSFT can you please clarify what code move you made? I looked at the files changes but I am not clear. The code seems to be in sync with what's in docs?

**Comment by KalyanChanumolu-MSFT** [comment]
@SnehaGunda The docs reference to line numbers 76, 91 and 110 in the [Review the code](https://docs.microsoft.com/en-us/azure/cosmos-db/create-sql-api-dotnet#review-the-code) section.
However, your earlier pull request added a couple of methods to the middle of the DocumentDBRepository.cs file and the line number references got changed.
The customer was referring the to same.
I have adjusted the same to match with the line numbers on the document.

**Comment by KalyanChanumolu-MSFT** [comment]
@SnehaGunda Could you please review this PR.

**Comment by SnehaGunda** [comment]
@KalyanChanumolu-MSFT I am getting rid of the line number references in the doc, instead just call out the method names, I have a PR that's building https://github.com/MicrosoftDocs/azure-docs-pr/pull/70125 . Please check the live content after 3PM content publishing today or you can see the files changed tab in that PR for updates I made. 

I don't think your updates are needed anymore with the changes I made to the doc? please confirm.

**Comment by KalyanChanumolu-MSFT** [comment]
Thanks @SnehaGunda 
I will abandon this PR

**Pull request closed without merging**
