### PR TITLE
Merge pull request #1 from Azure-Samples/master

### PR DESCRIPTION
**Pull request by SnehaGunda**
Merge pull request #13 from SnehaGunda/master

### CODE REVIEW

**Comment by SnehaGunda** [comment]
Fixes https://github.com/MicrosoftDocs/azure-docs/issues/23792

**Comment by SnehaGunda** [comment]
@ThomasWeiss @markjbrown I made some updates for the code sample to create and perform other operations on partitioned containers. can you please review. 

Addresses this Git issue: https://github.com/MicrosoftDocs/azure-docs/issues/23792

**Comment by ThomasWeiss** [comment]
@SnehaGunda This sample uses a pretty old version of the .NET SDK and I think we should expose the most up-to-date experience instead:
- In the references of the todoTests project, remove the Microsoft.Azure.Documents.Client reference
- Update the Microsoft.Azure.DocumentDB NuGet package to the latest version (2.2.3) and install it in the todoTests project as well
- Now you can use methods like `CreateDatabaseIfNotExistsAsync` and `CreateDocumentCollectionIfNotExistsAsync`, which simplifies the code

Let me know if you have questions or run into issues, thanks!

**Comment by harshan007** [comment]
@SnehaGunda I would echo what @ThomasWeiss said w.r.t this:

- In the references of the todoTests project, remove the Microsoft.Azure.Documents.Client reference
- Update the Microsoft.Azure.DocumentDB NuGet package to the latest version (2.2.3) and install it in the todoTests project as well

I tried the sample afresh and when i install latest DocumentDB from NuGet, the sample doesn't work and i had to remove Documents.Client reference. 

After this there is this issue of PartitionKey and i believe your commits should fix that.

**Comment by SnehaGunda** [comment]
@ThomasWeiss and @harshan007 Apologies for the long delay, I updated the package to the 2.2.3 version. When users download the sample and restore the Nuget packages, it should run successfully. I will now merge this PR.

**Pull request merged**
